// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyYXtcCq2_fqyouXRQYk_XF7MGbHkjF8',
    appId: '1:605340359244:web:7d62ac674fd52eedf9f2e9',
    messagingSenderId: '605340359244',
    projectId: 'deltahacks202',
    authDomain: 'deltahacks202.firebaseapp.com',
    databaseURL: 'https://deltahacks202-default-rtdb.firebaseio.com',
    storageBucket: 'deltahacks202.firebasestorage.app',
    measurementId: 'G-ECY6FRMNQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZps9ZVYudfMDyDE4RW2n0wN-k7uQ3cMs',
    appId: '1:605340359244:android:1f833e84978f94dcf9f2e9',
    messagingSenderId: '605340359244',
    projectId: 'deltahacks202',
    databaseURL: 'https://deltahacks202-default-rtdb.firebaseio.com',
    storageBucket: 'deltahacks202.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CBcEW5bLyjmFWoNBA0GBW_Nzv8uuH40',
    appId: '1:605340359244:ios:1c28a5f4dd93c86df9f2e9',
    messagingSenderId: '605340359244',
    projectId: 'deltahacks202',
    databaseURL: 'https://deltahacks202-default-rtdb.firebaseio.com',
    storageBucket: 'deltahacks202.firebasestorage.app',
    iosBundleId: 'com.example.fallDetectionV2.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4CBcEW5bLyjmFWoNBA0GBW_Nzv8uuH40',
    appId: '1:605340359244:ios:f4929acc351ea279f9f2e9',
    messagingSenderId: '605340359244',
    projectId: 'deltahacks202',
    databaseURL: 'https://deltahacks202-default-rtdb.firebaseio.com',
    storageBucket: 'deltahacks202.firebasestorage.app',
    iosBundleId: 'com.example.fallDetectionV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbyYXtcCq2_fqyouXRQYk_XF7MGbHkjF8',
    appId: '1:605340359244:web:e4d0a7a10708b99df9f2e9',
    messagingSenderId: '605340359244',
    projectId: 'deltahacks202',
    authDomain: 'deltahacks202.firebaseapp.com',
    databaseURL: 'https://deltahacks202-default-rtdb.firebaseio.com',
    storageBucket: 'deltahacks202.firebasestorage.app',
    measurementId: 'G-05EF75Y1PF',
  );

}